# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# 展開できる変数みたいなやつ
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9.2.0

version: 2
jobs:
  build_job:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: echo start
  
  d_job:
    <<: *defaults
    branches:
      only: 
      - master
    steps:
      - run: echo deploy

  
  f_job:
    <<: *defaults

    steps:
      - run: echo feature

workflows:
  version: 2
  build_flow:
    jobs:
      - build_job
      - d_job:
          requires:
            - build_job
      - f_job:
          requires:
            - build_job
      

